import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import pokemonApi from "../services/pokemonApi";
import { useState, useEffect } from "react";
import { useTheme } from "next-themes";
import Toogle from "../components/toogle";
import { MoonIcon, SunIcon } from "@radix-ui/react-icons";

const Home: NextPage = () => {
  const [loading, setLoading] = useState(false);
  const [pokemons, setPokemons] = useState([]);
  const { theme, setTheme } = useTheme();

  const toggleTheme = (value) => setTheme(value);

  async function getPokemons() {
    try {
      setLoading(true);
      const response = await pokemonApi.get("/pokemon?limit=10&offset=0");
      console.log(response.data);
      setPokemons(response.data);
      setLoading(false);
    } catch (error) {
      console.log(error);
      setLoading(false);
    }
  }

  useEffect(() => {
    getPokemons();
  }, []);

  if (loading) {
    return <p> Loading ....</p>;
  }

  //(newValue: "dark" | "light") => setTheme(newValue)

  console.log("THEME", theme);
  return (
    <div className={styles.container}>
      <Head>
        <title>Wiki Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>The current theme is {theme === "dark" ? "dark" : "light"}</h1>
        <Toogle
          value={theme}
          onValueChange={(newValue) => toggleTheme(newValue)}
          options={[
            {
              children: <SunIcon />,
              value: "light",
            },
            {
              children: <MoonIcon />,
              value: "dark",
            },
          ]}
        />

        {pokemons?.results?.map((pokemon) => (
          <p>{pokemon.name}</p>
        ))}

        <span> {pokemons.count} </span>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
