import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import pokemonApi from "../services/pokemonApi";
import { useState, useEffect } from "react";
import { useTheme } from "next-themes";
import Toogle from "../components/toogle";
import { MoonIcon, SunIcon } from "@radix-ui/react-icons";
import Container from "../components/container";
import NavBar from "../components/navbar";
import ContextMenu from "../components/contextMenu";

const Home: NextPage = () => {
  const [loading, setLoading] = useState(false);
  const [pokemons, setPokemons] = useState([]);
  const { theme, setTheme } = useTheme();

  const toggleTheme = (value) => setTheme(value);

  async function getPokemons() {
    try {
      setLoading(true);
      const response = await pokemonApi.get("/pokemon?limit=10&offset=0");
      console.log(response.data);
      setPokemons(response.data);
      setLoading(false);
    } catch (error) {
      console.log(error);
      setLoading(false);
    }
  }

  useEffect(() => {
    getPokemons();
  }, []);

  if (loading) {
    return <p> Loading ....</p>;
  }

  //(newValue: "dark" | "light") => setTheme(newValue)

  console.log("THEME", theme);
  return (
    <Container>
      <Head>
        <title>Wiki Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      {pokemons?.results?.map((pokemon) => (
        <p>{pokemon.name}</p>
      ))}

      <span> {pokemons.count} </span>

      <ContextMenu />

      <footer></footer>
    </Container>
  );
};

export default Home;
